### ISSUE TITLE
自动收拾垃圾会出现空白的提示

### ISSUE THREAD

**Issue by klarkxy** [blacksnipebiu/Auxilaryfunction#2]
![image](https://user-images.githubusercontent.com/6316992/201020058-25f4c758-30d4-458d-9420-bb254fc1b9ce.png)
本来是有具体的东西的，重启了之后就没有了，变成了空白

**Comment by blacksnipebiu** [comment]
这个跟我的mod应该没关系吧，我mod里没有跟这个有关的功能

**Comment by klarkxy** [comment]
![image](https://user-images.githubusercontent.com/6316992/201068511-4e9990c4-942f-4224-a57c-c4b9e233468d.png)
这个功能——

**Comment by blacksnipebiu** [comment]
1.8.7版本你可以试试
