### ISSUE TITLE
自动导航的问题

### ISSUE THREAD

**Issue by Aebestach** [blacksnipebiu/Auxilaryfunction#3]
你好，作者，这个mod非常棒，但是我现在遇到了一个问题。
本恒星系内，自动导航可以正常使用，并且可以使用跃迁。
但是横跨恒星系的话，自动导航就失效了。
是因为只支持恒星系内的导航吗

**Comment by blacksnipebiu** [comment]
是只支持选中行星导航，选中恒星导航确实应该做一下，有空的时候会把恒星导航的功能做掉的

**Comment by Aebestach** [comment]
是的，我也发现了，所以关闭了关闭了这个问题
