### ISSUE TITLE
當開啟自動填加科技對列，選擇退出遊戲而不是退出至桌面會紅字報錯

### ISSUE THREAD

**Issue by blacksnownight** [blacksnipebiu/Auxilaryfunction#5]
![QQ图片20230507123203](https://user-images.githubusercontent.com/128919146/236657968-c54183c1-d7e6-4757-8e30-505aff7bc36b.png)
https://youtu.be/B6_dlYvjB7E
就 額 標題都寫完了，視頻只是如何復現
LogOutput沒有出現任何錯誤或是特別的東西就不貼了

**Comment by blacksnipebiu** [comment]
修好了
